version: '2'

services:
  master:
    build: .
    image: jenkins-master
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - /usr/local/bin/docker:/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock